version: "3.9"
services:
    banking-transactions-app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: banking-transactions-app
        volumes:
            - ./:/var/www/app
            - vendor:/var/www/app/vendor
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        expose:
            - "9000"
        depends_on:
            - postgres
            - redis
        networks:
            - app-network
            
    nginx:
        image: nginx:latest
        container_name: banking-transactions-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - banking-transactions-app
        networks:
            - app-network

    postgres:
        image: postgres:15
        container_name: banking-transactions-postgres
        environment:
            POSTGRES_USER: banking_transactions
            POSTGRES_PASSWORD: banking_transactions
            POSTGRES_DB: banking_transactions
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network 
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app-network

volumes:
    postgres-data:
    vendor:

networks:
  app-network:
    driver: bridge  
